# Generated by Django 4.0.4 on 2022-05-26 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('n_identificacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_de_documento', models.IntegerField(choices=[(1, 'CC'), (2, 'CE'), (3, 'TI'), (4, 'NIT')])),
                ('n_de_documento', models.IntegerField()),
                ('programa_academico', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('celular', models.BigIntegerField()),
                ('eval', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lider_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrantes.integrante')),
            ],
        ),
    ]
