# Generated by Django 4.0.4 on 2022-05-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lider_I',
        ),
    ]
