# Generated by Django 4.0.4 on 2022-05-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0003_lider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante',
            name='n_de_documento',
        ),
    ]
