# Generated by Django 4.0.4 on 2022-05-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0004_remove_integrante_n_de_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lider',
            name='caso_emergencia',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lider',
            name='celular_emergencia',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lider',
            name='direccion',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lider',
            name='semestre',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
