# Generated by Django 4.0.4 on 2022-05-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('facultad', models.CharField(max_length=250)),
                ('programa_academico', models.CharField(max_length=250)),
                ('investigacion', models.CharField(max_length=250)),
                ('investigacion_asociado', models.CharField(max_length=250)),
                ('tematica', models.CharField(max_length=250)),
                ('justificacion', models.TextField(max_length=2000)),
            ],
        ),
    ]
