# Generated by Django 4.0.4 on 2022-05-23 05:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0002_docente_semillero_coordinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='n_emergencia',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
