# Generated by Django 4.0.4 on 2022-05-23 05:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0003_alter_docente_celular_alter_docente_n_emergencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='docente',
            name='n_emergencia',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
