# Generated by Django 4.0.4 on 2022-05-25 05:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0004_alter_docente_celular_alter_docente_n_emergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_C_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('actividad', models.CharField(max_length=100)),
                ('tipo_de_vinculacion', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion_c', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('actividad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.actividad_c_t')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematica', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('horas', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lengua', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(choices=[(1, 'BÁSICO'), (2, 'INTERMEDIO'), (3, 'AVANZADO')])),
            ],
        ),
        migrations.CreateModel(
            name='Informacion_Academica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.IntegerField(choices=[(1, 'PREGRADO'), (2, 'POSGRADOS')])),
                ('informacion_p', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('_a', models.CharField(max_length=100)),
                ('año', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_D_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('publicado', models.CharField(max_length=100)),
                ('año', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_De_Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion_p_i', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('actividad', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.actividad_i')),
                ('proyecto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.proyecto')),
                ('resultado', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.resultado_d_i')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_En_Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvlac_registrado', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('proyecto_i', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.proyecto_de_investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('n_identificacion', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lugar_expedicion', models.CharField(max_length=100)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('f_nacimiento', models.CharField(max_length=100)),
                ('direcccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('c_emergencia', models.CharField(max_length=100)),
                ('n_emergencia', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semillero_app.curso')),
                ('experiencia_en_investigacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='semillero_app.experiencia_en_investigacion')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semillero_app.idioma')),
                ('informacion_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semillero_app.informacion_academica')),
            ],
        ),
        migrations.AlterField(
            model_name='semillero',
            name='coordinador',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.coordinator'),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
