# Generated by Django 4.0.4 on 2022-05-25 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0005_actividad_c_t_actividad_i_curso_idioma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='coordinador',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='coordinador',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.semillero'),
            preserve_default=False,
        ),
    ]
