# Generated by Django 4.0.4 on 2022-05-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0006_remove_semillero_coordinador_coordinator_coordinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_academica',
            name='programa',
            field=models.IntegerField(choices=[(1, 'PREGRADO'), (2, 'POSGRADOS')], null=True),
        ),
    ]
