# Generated by Django 4.0.4 on 2022-05-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0007_alter_informacion_academica_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_academica',
            name='programa',
            field=models.IntegerField(choices=[(1, 'PREGRADO'), (2, 'POSGRADOS')], default=None),
            preserve_default=False,
        ),
    ]
