# Generated by Django 4.0.4 on 2022-05-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0008_alter_informacion_academica_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad_i',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='coordinador',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='experiencia_en_investigacion',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='informacion_academica',
        ),
        migrations.RemoveField(
            model_name='experiencia_en_investigacion',
            name='proyecto_i',
        ),
        migrations.RemoveField(
            model_name='proyecto_de_investigacion',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='proyecto_de_investigacion',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto_de_investigacion',
            name='resultado',
        ),
        migrations.DeleteModel(
            name='Actividad_C_T',
        ),
        migrations.DeleteModel(
            name='Actividad_I',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Experiencia_En_Investigacion',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Informacion_Academica',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='Proyecto_De_Investigacion',
        ),
        migrations.DeleteModel(
            name='Resultado_D_I',
        ),
    ]
