# Generated by Django 4.0.4 on 2022-05-28 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
        ('semillero_app', '0010_alter_semillero_facultad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='coordinator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coordinador.coordinador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semillero',
            name='justificacion',
            field=models.TextField(max_length=2000, verbose_name='JUSTIFICACIÓN DEL SEMILLERO DE INVESTIGACIÓN'),
        ),
    ]
