# Generated by Django 4.0.4 on 2022-05-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0011_semillero_coordinator_alter_semillero_justificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='coordinator',
        ),
    ]
