# Generated by Django 4.0.4 on 2022-05-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
        ('semillero_app', '0012_remove_semillero_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.coordinador'),
        ),
    ]
