# Generated by Django 4.0.4 on 2022-05-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0003_recibido_c_aval_recibido_c'),
        ('semillero_app', '0013_semillero_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrante.integrante'),
        ),
    ]
