# Generated by Django 4.0.4 on 2022-06-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0014_semillero_integrante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='integrante',
        ),
    ]
