# Generated by Django 4.0.4 on 2022-05-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_c', models.CharField(max_length=100, verbose_name='NOMBRE GRUPO/ COMITÉ')),
                ('actividad', models.CharField(max_length=100, verbose_name='ACTIVIDAD O TEMA')),
                ('tipo', models.CharField(max_length=100, verbose_name='TIPO DE VINCULACIÓN (Rol que desempeño)')),
                ('fecha', models.CharField(max_length=100, verbose_name='FECHA')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad_institucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion_c', models.IntegerField(choices=[(1, 'SI'), (2, 'NO')], verbose_name='Participa en Comité o Grupo de Trabajo')),
                ('actividad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.actividad_i')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematica', models.CharField(max_length=250, verbose_name='TEMÁTICA')),
                ('institucion', models.CharField(max_length=250, verbose_name='INSTITUCIÓN')),
                ('horas', models.CharField(max_length=250, verbose_name='HORAS')),
                ('fecha', models.CharField(max_length=100, verbose_name='FECHA')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lengua', models.CharField(max_length=100, verbose_name='Lengua')),
                ('nivel', models.IntegerField(choices=[(1, 'BÁSICO'), (2, 'INTERMEDIO'), (3, 'AVANZADO')], verbose_name='Indique el Nivel Alcanzado')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'BÁSICO'), (2, 'INTERMEDIO'), (3, 'AVANZADO')], verbose_name='Indique el Nivel Alcanzado')),
                ('information', models.TextField(max_length=2000, verbose_name='JUSTIFICACIÓN DEL SEMILLERO DE INVESTIGACIÓN')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion_P_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100, verbose_name='NOMBRE PROYECTO')),
                ('institucion', models.CharField(max_length=100, verbose_name='INSTITUCIÓN')),
                ('tipo_de_vinculacion', models.CharField(max_length=100, verbose_name='TIPO DE VINCULACIÓN (Rol desempeñado)')),
                ('año', models.CharField(max_length=100, verbose_name='AÑO')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_D_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='TIPO')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('publicado', models.CharField(max_length=100, verbose_name='PUBLICADO EN')),
                ('año', models.CharField(max_length=100, verbose_name='AÑO')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_i', models.IntegerField(choices=[(1, 'SI'), (2, 'NO')], verbose_name='Participa en Comité o Grupo de Trabajo')),
                ('participacion_p_i', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.participacion_p_i')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvlac', models.IntegerField(choices=[(1, 'SI'), (2, 'NO')], verbose_name='¿Tiene CvLAC registrado en Colciencias?')),
                ('Actividad_i', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.actividad_institucional')),
                ('proyecto_i', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.proyecto')),
                ('resultado_d_i', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.resultado_d_i')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('nombre', models.CharField(max_length=250, verbose_name='NOMBRE COMPLETO')),
                ('n_identificacion', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='NÚMERO DE IDENTIFICACIÓN')),
                ('f_nacimiento', models.CharField(max_length=100, verbose_name='FECHA DE NACIMIENTO')),
                ('lugar_expedicion', models.CharField(max_length=100, verbose_name='LUGAR DE EXPEDICIÓN ID')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='LUGAR DE NACIMIENTO')),
                ('celular', models.BigIntegerField(verbose_name='TELÉFONO/ CELULAR')),
                ('direcccion', models.CharField(max_length=100, verbose_name='DIRECCIÓN RESIDENCIA')),
                ('email', models.EmailField(max_length=200, verbose_name='CORREO ELECTRÓNICO')),
                ('c_emergencia', models.CharField(max_length=100, verbose_name='EN CASO DE EMERGENCIA LLAMAR A')),
                ('n_emergencia', models.BigIntegerField(verbose_name='NÚMERO DE CONTACTO')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.curso')),
                ('idioma', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.idioma')),
                ('informacion_academica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.informacion_c')),
            ],
        ),
    ]
