# Generated by Django 4.0.4 on 2022-06-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad_institucional',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='Actividad_i',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='proyecto_i',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='resultado_d_i',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='participacion_p_i',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='informacion_academica',
        ),
        migrations.DeleteModel(
            name='Actividad_i',
        ),
        migrations.DeleteModel(
            name='Actividad_institucional',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Experiencia',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Informacion_C',
        ),
        migrations.DeleteModel(
            name='Participacion_P_I',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='Resultado_D_I',
        ),
    ]
