# Generated by Django 4.0.4 on 2022-06-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('n_identificacion', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='NÚMERO DE IDENTIFICACIÓN')),
                ('nombre', models.CharField(max_length=250, verbose_name='NOMBRE COMPLETO')),
                ('f_nacimiento', models.CharField(max_length=100, verbose_name='FECHA DE NACIMIENTO')),
                ('lugar_expedicion', models.CharField(max_length=100, verbose_name='LUGAR DE EXPEDICIÓN ID')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='LUGAR DE NACIMIENTO')),
                ('celular', models.BigIntegerField(verbose_name='TELÉFONO/ CELULAR')),
                ('email', models.EmailField(max_length=200)),
                ('direcccion', models.CharField(max_length=100, verbose_name='DIRECCIÓN RESIDENCIA')),
                ('c_emergencia', models.CharField(max_length=100, verbose_name='EN CASO DE EMERGENCIA LLAMAR A')),
                ('n_emergencia', models.BigIntegerField(verbose_name='NÚMERO DE CONTACTO')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='NOMBRE DEL SEMILLERO')),
                ('facultad', models.CharField(max_length=250, verbose_name='FACULTAD')),
                ('programa_academico', models.CharField(max_length=250, verbose_name='PROGRMA ACADÉMICO')),
                ('investigacion', models.CharField(max_length=250, verbose_name='GRUPO DE INVESTIGACIÓN AL CUAL ESTÁ VINCULADO EL SEMILLERO')),
                ('investigacion_asociado', models.CharField(max_length=250, verbose_name='LÍNEA Y SUBLÍNEA DE INVESTIGACIÓN ASOCIADOS')),
                ('tematica', models.CharField(max_length=250, verbose_name='TÉMATICA DE ESTUDIO DEL SEMILLERO')),
                ('justificacion', models.TextField(max_length=2000, verbose_name='JUSTIFICACIÓN DEL SEMILLERO DE INVESTIGACIÓN')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semillerolist', to='semilleros.coordinador')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('tipo_de_solictante', models.CharField(max_length=100, verbose_name='TIPO DE SOLICTANTE')),
                ('nombre', models.CharField(max_length=250, verbose_name='NOMBRE COMPLETO')),
                ('n_identificacion', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='NÚMERO DE IDENTIFICACIÓN')),
                ('f_nacimiento', models.CharField(max_length=100, verbose_name='FECHA DE NACIMIENTO')),
                ('direcccion', models.CharField(max_length=100, verbose_name='DIRECCIÓN RESIDENCIA')),
                ('email', models.EmailField(max_length=200, verbose_name='CORREO ELECTRÓNICO')),
                ('lugar_expedicion', models.CharField(max_length=100, verbose_name='LUGAR DE EXPEDICIÓN ID')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='LUGAR DE NACIMIENTO')),
                ('celular', models.BigIntegerField(verbose_name='TELÉFONO/ CELULAR')),
                ('c_emergencia', models.CharField(max_length=100, verbose_name='EN CASO DE EMERGENCIA LLAMAR A')),
                ('n_emergencia', models.BigIntegerField(verbose_name='NÚMERO DE CONTACTO')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('semillero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semilleros.semillero')),
            ],
        ),
    ]
