# Generated by Django 4.0.4 on 2022-05-30 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso_F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso_F_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacion_i', models.BooleanField(default=True, verbose_name='¿Ha realizado cursos de formación de investigación? ')),
                ('curso_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrante.curso_f')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lengua', models.CharField(max_length=100, verbose_name='Lengua')),
                ('nivel', models.IntegerField(choices=[(1, 'BASICO'), (2, 'INTERMEDIO'), (3, 'AVANZADO')], verbose_name='Indique el Nivel Alcanzado')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=100, verbose_name='PROGRAMA')),
                ('ano_i', models.CharField(max_length=100, verbose_name='AÑO INGRESO')),
                ('semestre', models.CharField(max_length=100, verbose_name='SEMESTRE ACTUAL')),
                ('grado', models.CharField(max_length=100, verbose_name='FECHA DE GRADO')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_D_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('publicado', models.CharField(max_length=100)),
                ('ano_r', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_I_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('ano_p', models.CharField(max_length=100)),
                ('resultados_d_i', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrante.resultados_d_i')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('tipo_de_solictante', models.CharField(max_length=100, verbose_name='TIPO DE SOLICTANTE')),
                ('nombre', models.CharField(max_length=250, verbose_name='NOMBRE COMPLETO')),
                ('n_identificacion', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='NÚMERO DE IDENTIFICACIÓN')),
                ('f_nacimiento', models.CharField(max_length=100, verbose_name='FECHA DE NACIMIENTO')),
                ('direcccion', models.CharField(max_length=100, verbose_name='DIRECCIÓN RESIDENCIA')),
                ('email', models.EmailField(max_length=200, verbose_name='CORREO ELECTRÓNICO')),
                ('lugar_expedicion', models.CharField(max_length=100, verbose_name='LUGAR DE EXPEDICIÓN ID')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='LUGAR DE NACIMIENTO')),
                ('celular', models.BigIntegerField(verbose_name='TELÉFONO/ CELULAR')),
                ('c_emergencia', models.CharField(max_length=100, verbose_name='EN CASO DE EMERGENCIA LLAMAR A')),
                ('n_emergencia', models.BigIntegerField(verbose_name='NÚMERO DE CONTACTO')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('curso_f_i', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrante.curso_f_i')),
                ('idioma', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='integrante.idioma')),
                ('informacion_e', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrante.informacion_e')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacion_i', models.IntegerField(choices=[(1, 'SI'), (2, 'NO')], verbose_name='¿Tiene CvLAC registrado en Colciencias?')),
                ('formacion_p', models.BooleanField(default=True, verbose_name='¿Ha participado en Proyectos de Investigación?')),
                ('proyecto_i_p', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='integrante.proyecto_i_p')),
            ],
        ),
    ]
