# Generated by Django 4.0.4 on 2022-05-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE GRUPO/ COMITÉ')),
                ('actividad', models.CharField(max_length=100, verbose_name='ACTIVIDAD O TEMA')),
                ('tipo_vinculacion', models.CharField(max_length=100, verbose_name='TIPO DE VINCULACIÓN (Rol que desempeño)')),
                ('fecha', models.CharField(max_length=100, verbose_name='FECHA')),
            ],
        ),
        migrations.CreateModel(
            name='Aval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(verbose_name='JUSTIFICACIÓN DEL SEMILLERO DE INVESTIGACIÓN')),
                ('firma_d', models.CharField(max_length=100, verbose_name='Firma y Fecha - DOCENTE COORDINADOR DEL SEMILLERO')),
                ('firma_c', models.CharField(max_length=100, verbose_name='Firma y Fecha - COMITÉ DE INVESTIGACIONES DE LA FACULTAD')),
                ('aval_d', models.IntegerField(choices=[(1, 'APROBADO'), (2, 'NEGADO')])),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del semillero de interés (No es obligatorio): ')),
                ('linea', models.CharField(max_length=100, verbose_name='Línea y sublínea de investigación')),
                ('numero_h', models.CharField(max_length=100, verbose_name='Número de horas semanales que estaría dispuesto a dedicar al proyecto de investigación')),
                ('tipo', models.IntegerField(choices=[(1, 'Fase Única'), (2, 'Fase Doble'), (3, 'Fase Triple')], verbose_name='Tipo de Semillero al que aplica')),
            ],
        ),
        migrations.AddField(
            model_name='integrante',
            name='experiencia_i',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='integrante.experiencia_i'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultados_d_i',
            name='ano_r',
            field=models.CharField(max_length=100, verbose_name='AÑO'),
        ),
        migrations.AlterField(
            model_name='resultados_d_i',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='resultados_d_i',
            name='publicado',
            field=models.CharField(max_length=100, verbose_name='PUBLICADO EN'),
        ),
        migrations.AlterField(
            model_name='resultados_d_i',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='TIPO'),
        ),
        migrations.CreateModel(
            name='Actividades_I_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participado', models.BooleanField(default=True, verbose_name='Participa en Comité o Grupo de Trabajo ')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrante.actividad')),
            ],
        ),
        migrations.AddField(
            model_name='integrante',
            name='aval',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='integrante.aval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrante',
            name='linea',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='integrante.linea'),
            preserve_default=False,
        ),
    ]
