# Generated by Django 4.0.4 on 2022-05-30 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0002_actividad_aval_linea_integrante_experiencia_i_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibido_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_s', models.CharField(max_length=100, verbose_name='Firma Solicitante')),
                ('firma_r', models.CharField(max_length=100, verbose_name='Firma Recibido')),
            ],
        ),
        migrations.AddField(
            model_name='aval',
            name='recibido_c',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='integrante.recibido_c'),
            preserve_default=False,
        ),
    ]
