# Generated by Django 4.0.4 on 2022-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0003_recibido_c_aval_recibido_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades_i_i',
            name='participado',
            field=models.IntegerField(choices=[(1, 'SI'), (2, 'NO')], verbose_name='Participa en Comité o Grupo de Trabajo'),
        ),
        migrations.AlterField(
            model_name='curso_f_i',
            name='formacion_i',
            field=models.IntegerField(choices=[(1, 'SI'), (2, 'NO')], verbose_name='¿Ha realizado cursos de formación de investigación?'),
        ),
    ]
