# Generated by Django 4.0.4 on 2022-06-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrante', '0004_alter_actividades_i_i_participado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades_i_i',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='aval',
            name='recibido_c',
        ),
        migrations.RemoveField(
            model_name='curso_f_i',
            name='curso_f',
        ),
        migrations.RemoveField(
            model_name='experiencia_i',
            name='proyecto_i_p',
        ),
        migrations.RemoveField(
            model_name='proyecto_i_p',
            name='resultados_d_i',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='aval',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='curso_f_i',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='experiencia_i',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='informacion_e',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='linea',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Actividades_I_I',
        ),
        migrations.DeleteModel(
            name='Aval',
        ),
        migrations.DeleteModel(
            name='Curso_F',
        ),
        migrations.DeleteModel(
            name='Curso_F_I',
        ),
        migrations.DeleteModel(
            name='Experiencia_I',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Informacion_E',
        ),
        migrations.DeleteModel(
            name='Linea',
        ),
        migrations.DeleteModel(
            name='Proyecto_I_P',
        ),
        migrations.DeleteModel(
            name='Recibido_C',
        ),
        migrations.DeleteModel(
            name='Resultados_D_I',
        ),
    ]
