# Generated by Django 4.0.4 on 2022-06-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0015_remove_semillero_integrante'),
        ('integrante', '0005_remove_actividades_i_i_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='semillero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.semillero'),
        ),
    ]
